GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWQiOiI2NGRlNDczNTYxY2VkMDAzOWQxZjYyODAiLCJpYXQiOjE2OTIyODg5NDksImV4cCI6MTY5MjI5MjU0OX0.kdYW157_lO8DdMusLQBVQ5M9ScT814bLcrdub1bdmsg

{
  "title": "title4",
  "author": "author4",
  "url": "url4",
  "likes": 3,
  "userId": "64de472a4527a597117affd3" 
}

###
DELETE http://localhost:3003/api/blogs/64de481cbf8c724ec834e492
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWQiOiI2NGRlNDczNTYxY2VkMDAzOWQxZjYyODAiLCJpYXQiOjE2OTIyODk1NjQsImV4cCI6MTY5MjI5MzE2NH0.OZbxz0p9EYKdwSj9NkmvNHoTXGCH86RQ1-LgIchp3LU

# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjRkZDRhMzc4OWY1ZDkxMjE1ODM4MWZiIiwiaWF0IjoxNjkyMjg3NjM4LCJleHAiOjE2OTIyOTEyMzh9.DJ2BuFZxBNbyJFC1OhU1x0qWT645osXsxGiXGNmaB98
# id: 64dda061a2112fd409cfba59

# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWQiOiI2NGRlNDczNTYxY2VkMDAzOWQxZjYyODAiLCJpYXQiOjE2OTIyODk1NjQsImV4cCI6MTY5MjI5MzE2NH0.OZbxz0p9EYKdwSj9NkmvNHoTXGCH86RQ1-LgIchp3LU
# id: 64dd4a3789f5d912158381fb