GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWQiOiI2NGRlNDczNTYxY2VkMDAzOWQxZjYyODAiLCJpYXQiOjE2OTIyOTkyNDQsImV4cCI6MTY5MjMwMjg0NH0.o4C8HgYMcBE58HQGSRlCtLQkEeFIGkLMYPKB699TSy4

{
  "title": "title5",
  "author": "author5",
  "url": "url5",
  "likes": 3,
  "userId": "64de472a4527a597117affd3" 
}

###
DELETE http://localhost:3003/api/blogs/64de481cbf8c724ec834e492
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWQiOiI2NGRlNDczNTYxY2VkMDAzOWQxZjYyODAiLCJpYXQiOjE2OTIyOTkyNDQsImV4cCI6MTY5MjMwMjg0NH0.o4C8HgYMcBE58HQGSRlCtLQkEeFIGkLMYPKB699TSy4

# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjRkZDRhMzc4OWY1ZDkxMjE1ODM4MWZiIiwiaWF0IjoxNjkyMjg3NjM4LCJleHAiOjE2OTIyOTEyMzh9.DJ2BuFZxBNbyJFC1OhU1x0qWT645osXsxGiXGNmaB98
# id: 64dda061a2112fd409cfba59

# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWQiOiI2NGRlNDczNTYxY2VkMDAzOWQxZjYyODAiLCJpYXQiOjE2OTIyODk1NjQsImV4cCI6MTY5MjI5MzE2NH0.OZbxz0p9EYKdwSj9NkmvNHoTXGCH86RQ1-LgIchp3LU
# id: 64dd4a3789f5d912158381fb